version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5
        working_directory: ~/repo
    steps:
      - checkout
      - run: # circleci の ruby のコンテナの bundler のバージョンは古いので update する
        name: bundle update
        command: gem install bundler:1.16.1
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
          - run:
            name: install dependencies
            command: |
              bundle install --jobs=4 --retry=3 --path vendor/bundle
          - save_cache:
            paths:
              - ./vendor/bundle
            key: v1-dependencies-{{ checksum "Gemfile.lock" }}
